# Generated by Django 5.0.6 on 2024-07-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=60)),
                ('tematica', models.CharField(max_length=60)),
                ('correo_corporativo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gestiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('correo_corporativo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Soluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('fecha_inicio_de_servicio', models.DateField()),
                ('solucionado', models.BooleanField()),
            ],
        ),
    ]
