# Generated by Django 5.0.6 on 2024-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesorias',
            options={'verbose_name': 'Asesoria', 'verbose_name_plural': 'Asesorias'},
        ),
        migrations.AlterModelOptions(
            name='capacitaciones',
            options={'ordering': ['cliente'], 'verbose_name': 'Capacitacion', 'verbose_name_plural': 'Capacitaciones'},
        ),
        migrations.AlterModelOptions(
            name='gestiones',
            options={'ordering': ['cliente', 'correo_corporativo'], 'verbose_name': 'Gestion', 'verbose_name_plural': 'Gestiones'},
        ),
        migrations.AlterModelOptions(
            name='soluciones',
            options={'verbose_name': 'Solucion', 'verbose_name_plural': 'Soluciones'},
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='tematica',
            field=models.CharField(default='', max_length=60),
        ),
    ]
